services:
  # picvault-backend:
  #   build:
  #     context: ./backend
  #   depends_on:
  #     - mysql-db
  #   ports:
  #     - 8080:8080

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RNADOM_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped